### ISSUE TITLE
TypeError: from_csv() missing 1 required positional argument: 'input_fields'

### ISSUE THREAD

**Issue by ashishpatel26** [PacktPublishing/Practical-Deep-Learning-at-Scale-with-MLFlow#1]
Each time we encounter this error while executing this code.

Note: This is facing in [Chapter01 ](https://github.com/PacktPublishing/Practical-Deep-Learning-at-Scale-with-MLFlow/tree/main/chapter01)and [Chapter02](https://github.com/PacktPublishing/Practical-Deep-Learning-at-Scale-with-MLFlow/tree/main/chapter02)

**Code :** 
```python
datamodule = TextClassificationData.from_csv(
    input_fields="review", # error is here. may be it's typo error
    target_fields="sentiment",
    train_file="data/imdb/train.csv",
    val_file="data/imdb/valid.csv",
    test_file="data/imdb/test.csv"
)
```
```python
Traceback (most recent call last):
  File "d:/Books/Practical Deep learning at Scale with mlflow/chapter02/first_dl_with_mlflow.py", line 8, in <module>
    datamodule = TextClassificationData.from_csv(
TypeError: from_csv() missing 1 required positional argument: 'input_field'
```

**Comment by yliu2018** [comment]
Thanks for your feedback. This is due to recent API change of lightning-flash, where the `input_fields` has been changed to `input_field`.  
In order to provide least friction to the learning experience, I have updated README.md to install lightning-flash version 0.5.0 with related dependencies so that this should work out-of-box for chapter 1 and chapter 2.
Please let me know if you are able to run the code as it is once you re-create your virtual environment by following the updated README.md.  I will close this issue in two days.
